api:
  build: ./api
  volumes:
    - ./api/src:/usr/src/app/src/
  command: npm run dev

app:
  build: ./app
  volumes:
    - ./app/src:/usr/src/app/src
    - ./app/public:/usr/src/app/public
  command: npm start

nginx:
  build: ./nginx
  ports:
    - '80:80'
    - '443:443'
  links:
    - api
    - app
